<a href="https://colab.research.google.com/github/Jeromy0515/machine-learning/blob/main/logistic_regression/grape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 데이터 입력
grape = np.array([[19, 300, 0], [20, 500, 0], [18, 400, 0],[25, 500, 1], [27, 700, 1], [28, 600, 1]])

In [ ]:
x = grape[:, :2] # 전체 행 중0-1열
y = grape[:, 2]  # 전체 행 중 2열

print(x)
print(y)

[[ 19 300]
 [ 20 500]
 [ 18 400]
 [ 25 500]
 [ 27 700]
 [ 28 600]]
[0 0 0 1 1 1]


In [ ]:
# 로지스틱 회귀 알고리즘으로 학습
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() # LR모델생성
model.fit(x, y) # 학습
print(model.coef_) # 가중치 출력
model.coef_
print(model.intercept_) # 편향 출력
# 가중치(weight)는 각 입력 신호가 결과 출력에 미치는 중요도를 조절하는 매개변수
# 편향(bias)은 뉴런의 활성화를 조절하는 매개변수, 활성화 조건 설정

[[0.71665314 0.04838074]]
[-40.31573036]


In [ ]:
# 예측
print(model.predict([[22, 600]]))
print(model.predict([[20, 500]]))

[1]
[0]


In [ ]:
print(model.score(x, y)) # 6 개로 학습했고, 그거를 다시 예측했으니 소스가 좋을수밖에 없음
# test set이 없음

1.0


In [ ]:
size = float(input('포도 한알의 크기는(mm): '))
weight = float(input('포도 한 송이의 무게는(g): '))
result = model.predict([[size, weight]])
if result == 1:
  print('거봉')
else:
  print('일반 포도')

포도 한알의 크기는(mm): 20
포도 한 송이의 무게는(g): 450
일반 포도
